[package]
name = "userspace-fw-client"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.0.30", features = ["derive"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
shared = { path = "../shared" }
