[package]
name = "userspace-fw-daemon"
version = "0.1.0"
edition = "2021"


[dependencies]
iptables = "0.5.0"
nfq = "0.2.5"
signal-hook = "0.3.14"
shared = { path = "../shared" }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
