[package]
name = "shared"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
clap = { version = "4.0.30", features = ["derive"] }